### ISSUE TITLE
数据库报错了，报错信息如下

### ISSUE THREAD

**Issue by ffiamz** [sebuaa2019/Team109#13]
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, logManage, sessions
Running migrations:
  Applying admin.0004_auto_20181127_2352...Traceback (most recent call last):
  File "D:\Anaconda3\envs\django2\lib\site-packages\django\db\models\options.py", line 564, in get_field
    return self.fields_map[field_name]
KeyError: 'user_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "D:\Anaconda3\envs\django2\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "D:\Anaconda3\envs\django2\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "D:\Anaconda3\envs\django2\lib\site-packages\django\core\management\base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "D:\Anaconda3\envs\django2\lib\site-packages\django\core\management\base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "D:\Anaconda3\envs\django2\lib\site-packages\django\core\management\base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "D:\Anaconda3\envs\django2\lib\site-packages\django\core\management\commands\migrate.py", line 203, in handle
    fake_initial=fake_initial,
  File "D:\Anaconda3\envs\django2\lib\site-packages\django\db\migrations\executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "D:\Anaconda3\envs\django2\lib\site-packages\django\db\migrations\executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "D:\Anaconda3\envs\django2\lib\site-packages\django\db\migrations\executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "D:\Anaconda3\envs\django2\lib\site-packages\django\db\migrations\migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "D:\Anaconda3\envs\django2\lib\site-packages\django\db\migrations\operations\fields.py", line 216, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "D:\Anaconda3\envs\django2\lib\site-packages\django\db\backends\sqlite3\schema.py", line 127, in alter_field
    super().alter_field(model, old_field, new_field, strict=strict)
  File "D:\Anaconda3\envs\django2\lib\site-packages\django\db\backends\base\schema.py", line 495, in alter_field
    new_db_params = new_field.db_parameters(connection=self.connection)
  File "D:\Anaconda3\envs\django2\lib\site-packages\django\db\models\fields\related.py", line 966, in db_parameters
    return {"type": self.db_type(connection), "check": self.db_check(connection)}
  File "D:\Anaconda3\envs\django2\lib\site-packages\django\db\models\fields\related.py", line 963, in db_type
    return self.target_field.rel_db_type(connection=connection)
  File "D:\Anaconda3\envs\django2\lib\site-packages\django\db\models\fields\related.py", line 878, in target_field
    return self.foreign_related_fields[0]
  File "D:\Anaconda3\envs\django2\lib\site-packages\django\db\models\fields\related.py", line 632, in foreign_related_fields
    return tuple(rhs_field for lhs_field, rhs_field in self.related_fields if rhs_field)
  File "D:\Anaconda3\envs\django2\lib\site-packages\django\db\models\fields\related.py", line 619, in related_fields
    self._related_fields = self.resolve_related_fields()
  File "D:\Anaconda3\envs\django2\lib\site-packages\django\db\models\fields\related.py", line 612, in resolve_related_fields
    else self.remote_field.model._meta.get_field(to_field_name))
  File "D:\Anaconda3\envs\django2\lib\site-packages\django\db\models\options.py", line 566, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
django.core.exceptions.FieldDoesNotExist: User has no field named 'user_id'
(django2)

**Comment by ffiamz** [comment]
哪个部分出问题了

**Comment by waveliu98** [comment]
workspace.xml可能被改动了，我传一个我这里默认的

**Comment by ffiamz** [comment]
现在时日志界面显示不出来了
D:\web\Apache24\htdocs\Team109\RobotSrc\myweb\apps\logManage\views.py:45: UnorderedOb
jectListWarning: Pagination may yield inconsistent results with an unordered object_l
ist: <class 'logManage.models.logs'> QuerySet.
  paginator = Paginator(log_list,15)

**Comment by ffiamz** [comment]
之前用的和这个是一个Paginator类吗

**Comment by waveliu98** [comment]
是啊 这部分我没改 我这里也不知道为什么显示不出来

**Comment by waveliu98** [comment]
不过我这里没有你那个报错 只是页面上没东西 我怀疑是我html改岔了

**Comment by ffiamz** [comment]
显示不出来是因为你应该render mylog.html而非index.html，index.html当然是空的

**Comment by ffiamz** [comment]
之后的界面我弄吧
